insert into stock( stock_name, current_price, created, last_updated) values('NIFTY 50',	11545.55, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into stock( stock_name, current_price, created, last_updated) values('SUNPHARMA',	392.80, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into stock( stock_name, current_price, created, last_updated) values('BAJFINANCE',	3604.95, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into stock( stock_name, current_price, created, last_updated) values('IOC',	150.35, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into stock( stock_name, current_price, created, last_updated) values('BAJAJFINSV',	7869.05, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into stock( stock_name, current_price, created, last_updated) values('ULTRACEMCO',	4530.45, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into stock( stock_name, current_price, created, last_updated) values('LT',	1528.60, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into stock( stock_name, current_price, created, last_updated) values('GRASIM',	908.7, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into stock( stock_name, current_price, created, last_updated) values('RELIANCE',	1277.15, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into stock( stock_name, current_price, created, last_updated) values( 'CIPLA',	547.95, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into stock( stock_name, current_price, created, last_updated) values( 'HEROMOTOCO',	2418.85, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into stock( stock_name, current_price, created, last_updated) values( 'ADANIPORTS',	402.8, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into stock( stock_name, current_price, created, last_updated) values( 'SBIN',	358.95, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into stock( stock_name, current_price, created, last_updated) values( 'INDUSINDBK',	1489.9, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into stock( stock_name, current_price, created, last_updated) values( 'BHARTIARTL',	359.5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into stock( stock_name, current_price, created, last_updated) values( 'ICICIBANK',	428.8, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into stock( stock_name, current_price, created, last_updated) values( 'AXISBANK',	787.50, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into stock( stock_name, current_price, created, last_updated) values( 'DRREDDY',	2607.70, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into stock( stock_name, current_price, created, last_updated) values( 'TATAMOTORS',	155.10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into stock( stock_name, current_price, created, last_updated) values( 'IBULHSGFIN',	689.65, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into stock( stock_name, current_price, created, last_updated) values( 'POWERGRID',	201.4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into stock( stock_name, current_price, created, last_updated) values( 'JSWSTEEL',	262.25, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into stock( stock_name, current_price, created, last_updated) values( 'ONGC',	152.4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into stock( stock_name, current_price, created, last_updated) values( 'TATASTEEL',	467.85, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into stock( stock_name, current_price, created, last_updated) values( 'HINDALCO',	197.4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into stock( stock_name, current_price, created, last_updated) values( 'BAJAJ-AUTO',	2772.10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into stock( stock_name, current_price, created, last_updated) values( 'VEDL',	161.6, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into stock( stock_name, current_price, created, last_updated) values( 'BPCL',	359.15, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into stock( stock_name, current_price, created, last_updated) values( 'M&M',	632.8, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into stock( stock_name, current_price, created, last_updated) values( 'KOTAKBANK',	1467.95, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into stock( stock_name, current_price, created, last_updated) values( 'NTPC',	128.8, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into stock( stock_name, current_price, created, last_updated) values( 'WIPRO',	265, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into stock( stock_name, current_price, created, last_updated) values( 'HINDUNILVR',	1741, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into stock( stock_name, current_price, created, last_updated) values( 'TECHM',	675.25, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into stock( stock_name, current_price, created, last_updated) values( 'INFY',	711.95, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into stock( stock_name, current_price, created, last_updated) values( 'BRITANNIA',	2753.95, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into stock( stock_name, current_price, created, last_updated) values( 'ZEEL',	331, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into stock( stock_name, current_price, created, last_updated) values( 'EICHERMOT',	18808.4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into stock( stock_name, current_price, created, last_updated) values( 'INFRATEL',	259.4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into stock( stock_name, current_price, created, last_updated) values( 'HDFCBANK',	2380.9, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into stock( stock_name, current_price, created, last_updated) values( 'MARUTI',	5960, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into stock( stock_name, current_price, created, last_updated) values( 'HDFC',	2229, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into stock( stock_name, current_price, created, last_updated) values( 'ITC',	273.6, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into stock( stock_name, current_price, created, last_updated) values( 'COALINDIA',	228.55, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into stock( stock_name, current_price, created, last_updated) values( 'ASIANPAINT',	1316.1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into stock( stock_name, current_price, created, last_updated) values( 'HCLTECH',	1020.1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into stock( stock_name, current_price, created, last_updated) values( 'YESBANK',	91.4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into stock( stock_name, current_price, created, last_updated) values( 'TCS',	2133.5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into stock( stock_name, current_price, created, last_updated) values( 'GAIL',	146.95, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
insert into stock( stock_name, current_price, created, last_updated) values( 'UPL',	637.8, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);